IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE '%Query%')
BEGIN
CREATE TABLE Query
(
ActorName VARCHAR(100) NOT NULL UNIQUE,
MovieName VARCHAR(100) NOT NULL,
Created_By VARCHAR(200) NOT NULL,
Created_DATE DATETIME NOT NULL
);
END

SELECT * FROM Query