CREATE TABLE CODE_ACADEMY
(
  CODE VARCHAR(100),
  ACADEMY VARCHAR(100),
  TRAINING_Per_Week INT,
  CREATED_DATE DATETIME,
  CREATED_BY VARCHAR(200),
  MODIFIED_DATE DATETIME,
  MODIFIED_BY VARCHAR(200)
);


--- CLAUSES - CREATE, TABLE
--- TABLE NAME - CODE_ACADEMY
--- COLUMNS - CODE, ACADEMY, TRAINING_Per_Week, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_DATE
--- DATA TYPES - VARCHAR(100), INT, DATETIME
