IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE '%AWARDS%')
BEGIN
DROP TABLE AWARDS;
END
GO
CREATE TABLE AWARDS
(
Id INTEGER PRIMARY KEY,
Name VARCHAR(100) UNIQUE NOT NULL,
Reason TEXT DEFAULT 'Not Applicable',
Created_Date DATETIME NOT NULL,
Created_By TEXT NOT NULL
);