INSERT INTO CODE_ACADEMY(CODE, ACADEMY,TRAINING_Per_Week,CREATED_BY,CREATED_DATE)
VALUES ('select * from code','chennai',1,'Thiru Arasu',GETDATE());

INSERT INTO CODE_ACADEMY(CODE, ACADEMY,TRAINING_Per_Week,CREATED_BY,CREATED_DATE)
VALUES ('select * from coders','coimbatore',2,'Arasu',DATEADD(dd,+1,GETDATE()));

INSERT INTO CODE_ACADEMY(CODE, ACADEMY,TRAINING_Per_Week,CREATED_BY,CREATED_DATE)
VALUES ('select * from cod','tirunelveli',3,'asu',DATEADD(dd,+2,GETDATE()));

INSERT INTO CODE_ACADEMY(CODE, ACADEMY,TRAINING_Per_Week,CREATED_BY,CREATED_DATE)
VALUES ('select * from de','Namakkal',4,'su',DATEADD(dd,+3,GETDATE()));



